[tool.pylint]
max-line-length = 120
disable = [
    "C0114",  # missing-module-docstring
    "W0622",  # redefined-builtin
    "C0301",  # line-too-long
    "R0913",  # too-many-arguments
    "R1705",  # no-else-return
    "R0912",  # too-many-branches
    "R0914",  # too-many-locals
    "C0103",  # invalid-name
    "W0613",  # unused-argument
    "E1101",  # no-member
    "R0903",  # too-few-public-methods
    "R0902",  # too-many-instance-attributes
    "W0201",  # attribute-defined-outside-init
    "W0718",  # broad-exception-caught
    "R0904",  # too-many-public-methods
    "W0107",  # unnecessary-pass
]
ignore = ["env"]  # Ignore the virtual environment folder

[tool.pytest.ini_options]
addopts = "-v"
