name: Linting & Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/requirements.txt
        python -m pip install -r requirements/requirements-tests.txt
    - name: Linting the code with pylint and flake8
      run: |
        pylint app/
    - name: Testing the code with pytest
      run: |
        pytest